blank_issues_enabled: true
contact_links:
  - name: Flat2VR Modding Discord
    url: https://discord.gg/flat2vr
    about: Report and discuss working or non-working games with the VR modding community.
