#pragma once

#include "xrfg/d3d12_history.hpp"
#include "xrfg/pose.hpp"

#include <d3d12.h>

#include <cstdint>
#include <limits>
#include <memory>
#include <mutex>
#include <span>

namespace xrfg {

struct D3D12FieldOfView {
    float angle_left{};
    float angle_right{};
    float angle_up{};
    float angle_down{};
};

struct D3D12ImageRect {
    std::uint32_t offset_x{};
    std::uint32_t offset_y{};
    std::uint32_t width{};
    std::uint32_t height{};
};

struct D3D12ReprojectionView {
    Pose pose{};
    D3D12FieldOfView fov{};
    // A zero-sized rectangle preserves the legacy full-resource contract for
    // direct synthesizer callers. The OpenXR layer always supplies the exact
    // submitted XrSwapchainSubImage rectangle.
    D3D12ImageRect image_rect{};
    // OpenXR callers provide the physical texture-array slice explicitly.
    // The sentinel preserves the legacy direct-call contract where one view
    // per array slice is supplied in slice order.
    std::uint32_t array_slice{
        std::numeric_limits<std::uint32_t>::max()};
};

struct D3D12FrameSynthesisTicket {
    std::uint64_t previous_serial{};
    std::uint64_t current_serial{};
    std::uint64_t fence_value{};
    std::uint32_t work_slot{};
    std::uint32_t synthetic_destination_index{
        std::numeric_limits<std::uint32_t>::max()};
    std::uint32_t current_destination_index{};
};

// Completed direct-queue GPU intervals for one NVIDIA Optical Flow pair.
// Values are expressed in microseconds and become available asynchronously
// after the pair's completion fence has passed.
struct D3D12NvidiaGpuTiming {
    std::uint64_t previous_serial{};
    std::uint64_t current_serial{};
    std::uint64_t pack_microseconds{};
    std::uint64_t eye0_microseconds{};
    std::uint64_t eye1_microseconds{};
    std::uint64_t composition_microseconds{};
    std::uint64_t total_microseconds{};
    std::uint32_t eye_count{};
};

enum class D3D12OpticalFlowBackend {
    fidelity_fx,
    nvidia,
};

enum class D3D12NvidiaPerformancePreset {
    slow,
    medium,
    fast,
};

enum class D3D12NvidiaInputScale {
    full,
    three_quarter,
    half,
};

struct D3D12NvidiaOpticalFlowOptions {
    D3D12NvidiaPerformancePreset preset{
        D3D12NvidiaPerformancePreset::medium};
    D3D12NvidiaInputScale input_scale{D3D12NvidiaInputScale::half};
    bool bidirectional{};
};

// Owns a rolling exclusive history lease. Each resource supports at most two
// bounded projection views. They ordinarily map one-to-one to at most two
// array slices, while a single slice may also contain two non-overlapping
// viewports for double-wide stereo. Each logical view is extracted into
// independent mono A/B/S resources. FidelityFX uses one persistent optical-flow
// context and temporal history per view; NVIDIA uses the same explicit A/B/S
// boundary with its serialized OFA adapter. submit_pair subtracts the
// image-space component generated by the OpenXR orientation/FOV mapping and
// renders residual scene motion in B's camera plane. The target camera must
// equal B, so current remains a bit-exact B copy and both outputs use B pose/FOV
// metadata. Translation remains depth-unaware. A repeated capture ticket is a
// legal unchanged-resource input: each view reuses only its own retained mono
// image while camera metadata advances. Submission calls never wait on the CPU.
class D3D12FrameSynthesizer final {
public:
    D3D12FrameSynthesizer() noexcept;
    ~D3D12FrameSynthesizer();

    D3D12FrameSynthesizer(const D3D12FrameSynthesizer&) = delete;
    D3D12FrameSynthesizer& operator=(const D3D12FrameSynthesizer&) = delete;

    [[nodiscard]] HRESULT initialize(
        ID3D12Device* device,
        ID3D12CommandQueue* queue,
        std::shared_ptr<D3D12SwapchainHistory> history,
        std::span<ID3D12Resource* const> current_destination_images,
        std::span<ID3D12Resource* const> synthetic_destination_images,
        DXGI_FORMAT view_format,
        // Native D3D12 OpenXR destinations use RENDER_TARGET. Shared D3D11
        // interop mirrors use COMMON at both API ownership boundaries.
        D3D12_RESOURCE_STATES release_state,
        D3D12OpticalFlowBackend backend =
            D3D12OpticalFlowBackend::fidelity_fx,
        D3D12NvidiaOpticalFlowOptions nvidia_options = {},
        bool enable_nvidia_gpu_timing = false) noexcept;

    [[nodiscard]] HRESULT submit_prime(
        const D3D12HistoryCaptureTicket& current,
        std::span<const D3D12ReprojectionView> current_source_views,
        std::uint32_t current_destination_index,
        D3D12FrameSynthesisTicket* ticket) noexcept;

    [[nodiscard]] HRESULT submit_pair(
        const D3D12HistoryCaptureTicket& current,
        std::span<const D3D12ReprojectionView> current_source_views,
        std::span<const D3D12ReprojectionView> synthetic_target_views,
        std::uint32_t synthetic_destination_index,
        std::uint32_t current_destination_index,
        D3D12FrameSynthesisTicket* ticket) noexcept;

    // Relinquishes the retained rolling source against its last GPU-use fence.
    // This is nonblocking and is required before history invalidation.
    [[nodiscard]] HRESULT retire_previous() noexcept;

    [[nodiscard]] HRESULT wait_for_idle() noexcept;

    // Returns S_OK and consumes one completed NVIDIA timing record, S_FALSE
    // when none is ready, or an error for an invalid output pointer/readback.
    [[nodiscard]] HRESULT consume_nvidia_gpu_timing(
        D3D12NvidiaGpuTiming* timing) noexcept;

    [[nodiscard]] bool initialized() const noexcept;

private:
    struct Impl;

    mutable std::mutex mutex_;
    std::unique_ptr<Impl> impl_;
};

}  // namespace xrfg
